import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {parseMatrix,parseCSV,photonPoints,parseRoute,exportRecords,excludedAddress} from './dist/core.js';
const require=createRequire(import.meta.url),ExcelJS=require('./dist/vendor/exceljs.min.js');
const rows=parseMatrix([['출발지','도착지'],['안산시청','정왕본동 행정복지센터'],['','상록구청']]);
assert.equal(rows.length,2);assert.equal(rows[1].status,'error');assert.equal(rows[0].sourceRow,2);
assert.equal(parseMatrix([['보고서'],[' 출발지 주소 ','도착지주소'],['안산시청','상록구청']])[0].sourceRow,3);
assert.throws(()=>parseMatrix([['출발지','도착지'],...Array(51).fill(['안산시청','상록구청'])]),/최대 50/);
assert.equal(parseMatrix([['출발지','도착지'],['대부북동 1','안산시청']])[0].invalid,true);
assert.equal(excludedAddress('안산시 단원구 선감동'),true);
assert.equal(parseMatrix([['출발지','도착지','출발위도','출발경도'],['안산시청','정왕동',37.322,126.831]])[0].origin.confirmed,true);
assert.equal(parseMatrix([['출발지','도착지','출발위도','출발경도'],['안산시청','정왕동',37.322,'']])[0].invalid,true);
assert.deepEqual(parseCSV('\uFEFF출발지,도착지\r\n"안산, 청사","시흥 ""정왕"""\r\n'),[['\uFEFF출발지','도착지'],['안산, 청사','시흥 "정왕"']]);
assert.throws(()=>parseCSV('"unfinished'),/따옴표/);
const features=[{geometry:{coordinates:[126.83,37.32]},properties:{city:'안산시',district:'단원구',name:'안산시청'}},{geometry:{coordinates:[126.75,37.35]},properties:{city:'시흥시',district:'정왕본동',name:'센터'}},{geometry:{coordinates:[126.75,37.35]},properties:{city:'시흥시',district:'신천동',name:'센터'}},{geometry:{coordinates:[126.58,37.25]},properties:{city:'안산시',name:'대부도'}}];
assert.equal(photonPoints({features},'센터').length,2);
const route=parseRoute({code:'Ok',routes:[{distance:12345,duration:999,geometry:{type:'LineString',coordinates:[[126.83,37.32],[126.75,37.35]]}}],waypoints:[]});
rows[0].route=route;rows[0].status='done';const exports=exportRecords(rows);assert.equal(exports[0]['편도도로거리(km)'],12.35);assert.equal(exports[1]['편도도로거리(km)'],'');
assert.throws(()=>parseRoute({code:'NoRoute'}),/경로/);
const book=new ExcelJS.Workbook();const sheet=book.addWorksheet('입력');sheet.addRows([['출발지','도착지'],['안산시청','=CMD(1)']]);
const bytes=await book.xlsx.writeBuffer();const read=new ExcelJS.Workbook();await read.xlsx.load(bytes);assert.equal(read.worksheets[0].getCell('B2').type,3);assert.equal(read.worksheets[0].getCell('A2').value,'안산시청');
const html=fs.readFileSync('dist/index.html','utf8');for(const [,path]of html.matchAll(/(?:src|href)="\.\/([^"?]+)"/g))assert.ok(fs.existsSync('dist/'+path),'Missing '+path);
assert.match(html,/대부도 제외/);assert.doesNotMatch(fs.readFileSync('dist/config.json','utf8'),/nominatim.openstreetmap.org/);
console.log('PASS: XLSX read/write; CSV; headers; missing addresses; row limit; coordinate validation; Daebudo exclusion; regional search filtering; routing failures; distance export; local assets.');

const fifty=parseMatrix([['출발지','도착지'],...Array(50).fill(['안산시청','상록구청'])]);
assert.equal(fifty.length,50);assert.equal(exportRecords(fifty).length,50);assert.equal(fifty[49].sourceRow,51);
assert.equal(JSON.parse(fs.readFileSync('dist/config.json','utf8')).maxRows,50);
assert.match(html,/id="limit-text">50/);console.log('PASS: 50 input rows and 50 output records; 51 rows rejected.');
